### ISSUE TITLE
Add activitywatch-git too

### ISSUE THREAD

**Issue by xeruf** [ActivityWatch/aur-activitywatch-bin#5]
There should be a `-git` package as well, since new updates (and their fixes) sometimes take a while until released. I am open to support you on that.

https://wiki.archlinux.org/title/VCS_package_guidelines

**Comment by ErikBjare** [comment]
The master branch is usually not very stable, so a `-git` package is a bad idea.

We might make a `-beta` package later though, but for now I'll update this package with beta releases I deem stable enough to push to powerusers (Arch users).
