### ISSUE TITLE
use updpkgsums to auto fill the checksum

### ISSUE THREAD

**Issue by asukaminato0721** [ActivityWatch/aur-activitywatch-bin#9]
tldr:

just run `updpkgsums` at the directory.

and here is my usual command for updating, packaging and testing.

```sh
updpkgsums && makepkg --printsrcinfo > .SRCINFO && makepkg -C -sf && namcap *.zst
```

ref <https://wiki.archlinux.org/title/PKGBUILD#Integrity>

**Comment by ErikBjare** [comment]
Nice, fixing now. Thanks!

The `namcap` stuff will have to wait (as it has in #2). Tried running it but throws a thousand warnings (due to PyInstaller mess) which I don't have the time to resolve right now.
